# -*- mode: python ; coding: utf-8 -*-

import os
import sys
from pathlib import Path

block_cipher = None

src_root = os.path.abspath('.')

a = Analysis(
    ['main_pyside.py'],
    pathex=[src_root],
    binaries=[],
    datas=[
        ('configs', 'configs'),
        ('assets', 'assets'),
        ('ai_models', 'ai_models'),
        ('database', 'database'),
        ('README.md', '.'),
    ],
    hiddenimports=[
        # Core
        'src.core.trading_system',
        'src.core.event_bus',
        'src.core.events',
        'src.core.thread_domains',
        'src.core.lock_manager',
        'src.core.circuit_breaker',
        'src.core.config_loader',
        'src.core.config_models',
        'src.core.config_validator',
        'src.core.config_writer',
        'src.core.container',
        'src.core.services_container',
        'src.core.account_manager',
        'src.core.account_monitor',
        'src.core.mt5_connection_manager',
        'src.core.mt5_symbol_helper',
        'src.core.cache_manager',
        'src.core.health_monitor',
        'src.core.hot_reload_manager',
        'src.core.interfaces',
        'src.core.loop_manager',
        'src.core.memory_utils',
        'src.core.metrics',
        'src.core.ml_predictor',
        'src.core.model_loader',
        'src.core.online_learner',
        'src.core.orchestrator',
        'src.core.paper_trading_engine',
        'src.core.profiler',
        'src.core.resource_governor',
        'src.core.risk_manager',
        'src.core.safety_monitor',
        'src.core.secrets_manager',
        'src.core.secure_config',
        'src.core.session_manager',
        'src.core.system_service_manager',
        'src.core.task_queue',
        'src.core.training_scheduler',
        'src.core.trading_system_db_integration',
        'src.core.auto_updater',
        # Services
        'src.core.services.base_service',
        'src.core.services.data_service',
        'src.core.services.execution_service',
        'src.core.services.ml_service',
        'src.core.services.monitoring_service',
        'src.core.services.mt5_connection_service',
        'src.core.services.news_service',
        'src.core.services.orchestrator_service',
        'src.core.services.portfolio_service',
        'src.core.services.position_manager',
        'src.core.services.risk_service',
        'src.core.services.signal_service',
        'src.core.services.trade_executor',
        'src.core.services.trading_service',
        # Trading sub
        'src.core.trading.gui_coordinator',
        'src.core.trading.health_check',
        'src.core.trading.ml_coordinator',
        'src.core.trading.model_fallback',
        'src.core.trading.nio_lazy_loader',
        'src.core.trading.trading_engine',
        'src.core.trading.utils',
        # GUI
        'src.gui.event_bridge',
        'src.gui.main_window',
        'src.gui.gui_dispatcher',
        'src.gui.styles',
        'src.gui.log_utils',
        'src.gui.sound_manager',
        'src.gui.animation_manager',
        'src.gui.custom_title_bar',
        'src.gui.settings_window',
        'src.gui.control_center_widget',
        'src.gui.dashboard_widget',
        'src.gui.analytics_tab',
        'src.gui.ai_training_widget',
        'src.gui.risk_management_widget',
        'src.gui.trading_modes_widget',
        'src.gui.trading_settings_widget',
        'src.gui.trading_system_adapter',
        'src.gui.unified_trading_settings',
        'src.gui.update_manager_widget',
        'src.gui.database_monitor_widget',
        'src.gui.api_tester',
        'src.gui.backtest_process',
        'src.gui.chart_theme_utils',
        'src.gui.widgets',
        'src.gui.widgets.bridges',
        'src.gui.widgets.defi_widget',
        'src.gui.widgets.graph_widgets',
        'src.gui.components',
        'src.gui.components.backtest',
        'src.gui.components.bridges',
        'src.gui.components.charts',
        'src.gui.components.models',
        'src.gui.dialogs',
        'src.gui.dialogs.directive_dialog',
        'src.gui.dialogs.documentation_dialog',
        'src.gui.dialogs.symbol_selection_dialog',
        'src.gui.models',
        'src.gui.models.table_models',
        # ML
        'src.ml.predictive_engine',
        'src.ml.predictor',
        'src.ml.model_factory',
        'src.ml.architectures',
        'src.ml.auto_trainer',
        'src.ml.championship',
        'src.ml.championship_retraining',
        'src.ml.consensus_engine',
        'src.ml.ensemble_predictor',
        'src.ml.feature_engineer',
        'src.ml.feature_importance',
        'src.ml.genetic_programming_core',
        'src.ml.model_paths',
        'src.ml.model_versioning',
        'src.ml.news_enrichment',
        'src.ml.orchestrator_env',
        'src.ml.ab_testing',
        'src.ml.ai_backtester',
        'src.ml.retrain_scheduler',
        'src.ml.rl_trade_manager',
        'src.ml.predictors',
        'src.ml.predictors.base',
        'src.ml.predictors.lightgbm_predictor',
        'src.ml.predictors.lstm_predictor',
        'src.ml.predictors.transformer_predictor',
        # DB
        'src.db.database_manager',
        'src.db.vector_db_manager',
        'src.db.multi_database_manager',
        'src.db.async_db_writer',
        'src.db.command_manager',
        'src.db.query_manager',
        'src.db.models',
        'src.db.adapters',
        'src.db.adapters.qdrant_adapter',
        'src.db.adapters.questdb_adapter',
        'src.db.adapters.redis_adapter',
        'src.db.adapters.timescaledb_adapter',
        'src.db.repositories',
        'src.db.repositories.candle_repository',
        'src.db.repositories.model_repository',
        'src.db.repositories.trade_repository',
        # Data
        'src.data.data_provider',
        'src.data.data_provider_manager',
        'src.data.data_collector',
        'src.data.data_sync_orchestrator',
        'src.data.news_collector',
        'src.data.market_feed',
        'src.data.simple_market_feed',
        'src.data.knowledge_graph_querier',
        'src.data.kg_sync_pipeline',
        'src.data.graph_db_manage',
        'src.data.binance_data_stream',
        'src.data.blockchain_provider',
        'src.data.crypto_exchange_provider',
        'src.data.multi_source_aggregator',
        'src.data.realtime_updater',
        'src.data.proactive_data_finder',
        'src.data.alternative_data_provider',
        'src.data.async_data_provider',
        'src.data.base_market_data_provider',
        'src.data.unified_news_connector',
        'src.data.web_scraper',
        # Risk
        'src.risk.risk_engine',
        'src.risk.circuit_breaker',
        'src.risk.position_sizer',
        'src.risk.volatility_forecaster',
        'src.risk.auto_configurator',
        # Strategies
        'src.strategies.breakout',
        'src.strategies.mean_reversion',
        'src.strategies.moving_average_crossover',
        'src.strategies.adaptive',
        'src.strategies.strategy_loader',
        'src.strategies.strategy_optimizer',
        'src.strategies.StrategyInterface',
        'src.strategies.features',
        # Analysis
        'src.analysis.backtester',
        'src.analysis.event_driven_backtester',
        'src.analysis.system_backtester',
        'src.analysis.gp_rd_manager',
        'src.analysis.market_regime_manager',
        'src.analysis.market_screener',
        'src.analysis.nlp_processor',
        'src.analysis.anomaly_detector',
        'src.analysis.stress_tester',
        'src.analysis.drift_detector',
        'src.analysis.simulators',
        'src.analysis.strategy_incubator',
        'src.analysis.strategy_optimizer',
        'src.analysis.synthetic_indices',
        'src.analysis.defi_analyzer',
        # Utils
        'src.utils.logger',
        'src.utils.worker',
        'src.utils.scheduler_manager',
        'src.utils.cache_manager',
        'src.utils.device_manager',
        'src.utils.file_utils',
        'src.utils.gui_thread_safety',
        'src.utils.retry_utils',
        'src.utils.torch_utils',
        'src.utils.analysis_utils',
        # Data enrichment
        'src.data_enrichment.defi_data_loader',
        'src.data_enrichment.load_data',
        'src.data_enrichment.yahoo_finance_loader',
        # Monitoring
        'src.monitoring',
        # Data models
        'src.data_models',
        'src._version',
        # PySide6
        'PySide6.QtWidgets',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWebChannel',
        'PySide6.QtWebEngineWidgets',
        'PySide6.QtSvg',
        'PySide6.QtSvgWidgets',
        # ML / Torch
        'torch',
        'torch.nn',
        'torch.optim',
        'torch.utils',
        'torch.utils.data',
        'lightgbm',
        'sklearn',
        'sklearn.preprocessing',
        'sklearn.metrics',
        'sklearn.model_selection',
        'numpy',
        'pandas',
        'scipy',
        'scipy.stats',
        'scipy.signal',
        'arch',
        'shap',
        'optuna',
        'joblib',
        'numba',
        'llvmlite',
        # NLP
        'sentence_transformers',
        'transformers',
        'transformers.pipeline',
        'sentencepiece',
        'nltk',
        'huggingface_hub',
        # Stable Baselines3
        'stable_baselines3',
        'stable_baselines3.ppo',
        'gymnasium',
        # DB drivers
        'sqlalchemy',
        'sqlalchemy.dialects.sqlite',
        'faiss',
        'neo4j',
        'redis',
        'psycopg2',
        'qdrant_client',
        # Web / Async
        'aiohttp',
        'asyncio',
        'websockets',
        'uvicorn',
        'fastapi',
        'httpx',
        'feedparser',
        'requests',
        # Crypto
        'ccxt',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'unittest',
        'pytest',
        '_pytest',
        'IPython',
        'jupyter',
        'notebook',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='GenesisTrading',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico.ico' if os.path.exists('assets/icon.ico.ico') else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='GenesisTrading',
)
